[package]
name = "alg-quickselect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
not_empty = { version = "0.1", default-features = false }


[features]
default = ["std"]
std = ["not_empty/std"]
